### ISSUE TITLE
Support for additional exporters

### ISSUE THREAD

**Issue by paddycarey** [justinbarrick/fluxcloud#6]
Hey, we'd like to add support for an additional exporter (Kafka or Redis, we're not sure yet honestly) to support some different use cases we have at my workplace. We're happy to do the work to add this functionality but I wanted to check if that was a desirable feature for this project before starting to write any code?

Thanks.

**Comment by justinbarrick** [comment]
Definitely desirable! I tried to abstract the exporters and formatters a bit so that we could add new ones as people needed it. 

You would need to add a new exporter: https://github.com/justinbarrick/fluxcloud/tree/master/pkg/exporters

You might also need a new formatter: https://github.com/justinbarrick/fluxcloud/tree/master/pkg/formatters

You’ll be the first one to add a new one, though, and going from one to two is going to be a little bit of work (for example, there’s currently no way to choose your exporter), but hopefully it’s not too bad.

Let me know or feel free to open a PR if you have any other questions! (I’m also on the Weave works slack as justin.m.barrick).

**Comment by justinbarrick** [comment]
@marratj was kind enough to implement our second exporter!

[His PR](https://github.com/justinbarrick/fluxcloud/pull/7) is a great example, [along with the tests I added](https://github.com/justinbarrick/fluxcloud/pull/8).

**Comment by justinbarrick** [comment]
[Sentry](https://sentry.io/welcome/) would be another good exporter.

**Comment by paddycarey** [comment]
Oh nice, the webhook exporter is probably perfect actually for my short-term needs. I'm going to close this issue for now and will just open a PR in future when I finally get some time to dig in here. Thanks @justinbarrick and @marratj!

**Comment by justinbarrick** [comment]
Awesome! I’ll give that a try!
